### PR TITLE
Contact creator

### PR DESCRIPTION
**Pull request by emmanuelvlad**
waiting till complete

### CODE REVIEW

**Comment by melkypie** [comment]
Yea probably for the best as I created the PR 5 minutes before you pushed your database changes

**Comment by emmanuelvlad** [comment]
You're trying to fetch the contacts from the database?

**Comment by melkypie** [comment]
Will try to add them to database when I get my dev environment set up.

**Comment by emmanuelvlad** [comment]
And btw, you can also use "phoneOption" and "phoneExtraOption" for things like the add button

**Comment by melkypie** [comment]
At first I thought about using them but thinking about people who would use it, many of them wouldn't have a clue that using spacebar(phoneExtraOption) would add contacts. So i just went with the regular arrow key setup as that would be more user friendly

**Comment by emmanuelvlad** [comment]
alright, I'm making all the fetching stuff

**Comment by melkypie** [comment]
Just looked at the code and you already did add the feature to add contacts to database. Come on atleast leave something for me to do.

**Pull request closed without merging**
